### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by jkque** [binance/binance-connector-node#43]
### Issue subject
Having an issue of Uncaught ReferenceError: process is not defined and pointing to utils.js line 65

### Steps to reproduce
- npm init vite@latest and create project using vue
- npm install @binance/connector
- use the package at main.js or anywhere (it will throw and error)

### Environment
Provide any relevant information about your setup, such as:
* "@binance/connector": "^1.4.0",
* v15.3.0
* Windows 11

**Comment by ishuen** [comment]
Hi. This is a known issue in Vue. Please check the project setting.
For more info:
1. node.js process: https://nodejs.org/dist/latest-v14.x/docs/api/process.html#process_process
2. node.js console: https://nodejs.org/dist/latest-v14.x/docs/api/console.html#console_console
3. no-console rule: https://eslint.org/docs/rules/no-console

**Comment by jkque** [comment]
@ishuen - thanks

I hope you will support native esm in the future for now will fork this repo.

**Comment by ishuen** [comment]
Thanks for the feedback. To be honest, we don't have the plan to support ES modules for now. We don't encourage the frontend integration due to the API restriction. If multiple users can access the same web application, it's very easy to hit the rate limit per IP. https://binance-docs.github.io/apidocs/spot/en/#limits
